import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/utils/authOptions";
import Hydrate from "./components/Hydrate";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // fetch user
  const session = await getServerSession(authOptions as any);

  return (
    <html lang="en">
      <body className="mx-64">
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires} />
          {children}
        </Hydrate>
      </body>
      <footer>
        <Link
          className="inline-block w-full text-center"
          href="https://www.flaticon.com/free-icons/basket"
          title="basket icons"
        >
          Basket icons created by Freepik - Flaticon
        </Link>
      </footer>
    </html>
  );
}
