import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/utils/authOptions";
import Hydrate from "./components/Hydrate";
import Link from "next/link";
import { Roboto, Lobster_Two } from "next/font/google";

// define main font
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-robot",
});

const lobster = Lobster_Two({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-lobster",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // fetch user
  const session = await getServerSession(authOptions as any);

  return (
    <html lang="en">
      <body className={`mx-64 ${roboto.className}`}>
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires} />
          {children}
        </Hydrate>
      </body>
      <footer>
        <Link
          className="inline-block w-full text-center"
          href="https://www.flaticon.com/free-icons/basket"
          title="basket icons"
        >
          Basket icons created by Freepik - Flaticon
        </Link>
      </footer>
    </html>
  );
}
